version: '3.9'
services:
mongo:
image: mongo:7
container_name: taskflow_mongo
restart: always
ports:
- "27017:27017"
environment:
MONGO_INITDB_ROOT_USERNAME: root
MONGO_INITDB_ROOT_PASSWORD: rootpassword
volumes:
- mongo_data:/data/db
backend:
b_build: ./backend
b_container_name: taskflow_backend
b_restart: always
b_ports:
- "5000:5000"
env_file: ./backend/.env
b_depends_on:
- mongo
frontend:
f_build: ./frontend
f_container_name: taskflow_frontend
f_restart: always
f_ports:
- "5173:5173"
f_depends_on:
- backend
f_volumes:
mongo_data: